/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "pantry-recipe-planner",
  "name": "Pantry Chef",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "I just bought 6 eggs, a bag of spinach and 500g of chicken",
      "does": "Adds all three to the pantry with expiry estimates."
    },
    {
      "say": "Plan dinners for this week, vegetarian on weekdays",
      "does": "Suggests recipes and fills the meal plan."
    },
    {
      "say": "Make me the shopping list",
      "does": "Builds the list from the plan minus your pantry."
    }
  ]
};
