/* Sample pantry and canned recipe suggestions used without an API key. */
var inDays = function (n) { return new Date(Date.now() + n * 864e5).toISOString().slice(0, 10); };
var DEMO_RECIPES = {
  recipes: [
    { title: 'Garlicky Spinach & Chicken Skillet', time_min: 25, servings: 2, difficulty: 'easy', why: 'Uses the chicken and spinach before they expire.', ingredients: [{ name: 'chicken thighs', qty: 400, unit: 'g' }, { name: 'spinach', qty: 150, unit: 'g' }, { name: 'garlic', qty: 3, unit: 'clove' }, { name: 'lemon', qty: 1, unit: 'pc' }, { name: 'olive oil', qty: 2, unit: 'tbsp' }, { name: 'parmesan', qty: 30, unit: 'g' }], steps: ['Season the chicken thighs with salt and pepper.', 'Heat the olive oil in a skillet over medium-high heat and sear the chicken for 6 minutes per side until golden and cooked through.', 'Move the chicken to a plate. Add the sliced garlic and cook for 1 minute until fragrant.', 'Add the spinach and the juice of half the lemon. Toss for 2 minutes until wilted.', 'Return the chicken, grate parmesan over the top, and serve with lemon wedges.'], nutrition: { kcal: 420, protein_g: 44, carbs_g: 6, fat_g: 24 } },
    { title: 'Cabbage & Egg Fried Rice', time_min: 20, servings: 2, difficulty: 'easy', why: 'Rescues half a cabbage and leftover rice.', ingredients: [{ name: 'rice', qty: 1.5, unit: 'cup' }, { name: 'cabbage', qty: 200, unit: 'g' }, { name: 'eggs', qty: 3, unit: 'pc' }, { name: 'soy sauce', qty: 2, unit: 'tbsp' }, { name: 'green onions', qty: 2, unit: 'pc' }, { name: 'sesame oil', qty: 1, unit: 'tsp' }], steps: ['Shred the cabbage finely and slice the green onions.', 'Scramble the eggs in a hot oiled wok for 1 minute and set aside.', 'Stir-fry the cabbage for 4 minutes until it starts to char.', 'Add the rice and soy sauce and fry for 5 minutes, pressing the rice against the pan.', 'Fold the eggs back in, drizzle with sesame oil and top with green onions.'], nutrition: { kcal: 460, protein_g: 18, carbs_g: 62, fat_g: 15 } },
    { title: 'Creamy Tomato Pasta', time_min: 30, servings: 2, difficulty: 'easy', why: 'Turns pantry staples and the cream into a fast dinner.', ingredients: [{ name: 'pasta', qty: 200, unit: 'g' }, { name: 'canned tomatoes', qty: 1, unit: 'can' }, { name: 'heavy cream', qty: 120, unit: 'ml' }, { name: 'garlic', qty: 2, unit: 'clove' }, { name: 'basil', qty: 1, unit: 'pc' }, { name: 'parmesan', qty: 40, unit: 'g' }], steps: ['Boil the pasta in salted water for 10 minutes or until al dente.', 'Meanwhile, sauté the garlic in oil for 1 minute, then add the tomatoes and simmer for 12 minutes.', 'Stir in the cream and simmer for 2 minutes more.', 'Toss the drained pasta with the sauce, a splash of pasta water and the parmesan.', 'Tear basil over the top and serve.'], nutrition: { kcal: 610, protein_g: 20, carbs_g: 78, fat_g: 24 } },
  ],
};
var SAMPLE_PANTRY = [
    { name: 'chicken thighs', qty: 500, unit: 'g', exp: inDays(1) }, { name: 'spinach', qty: 200, unit: 'g', exp: inDays(2) },
    { name: 'heavy cream', qty: 200, unit: 'ml', exp: inDays(3) }, { name: 'cabbage', qty: 0.5, unit: 'pc', exp: inDays(6) },
    { name: 'eggs', qty: 6, unit: 'pc', exp: inDays(12) }, { name: 'parmesan', qty: 120, unit: 'g', exp: inDays(25) },
    { name: 'rice', qty: 1, unit: 'kg', exp: null }, { name: 'pasta', qty: 500, unit: 'g', exp: null },
    { name: 'canned tomatoes', qty: 2, unit: 'can', exp: null }, { name: 'garlic', qty: 6, unit: 'clove', exp: inDays(20) },
    { name: 'soy sauce', qty: 250, unit: 'ml', exp: null }, { name: 'lemon', qty: 1, unit: 'pc', exp: inDays(9) },
  ];
